name: brain_dev_firebase_message
description: "A brain_dev_firebase_message new Flutter project."
version: 1.0.8
homepage: https://github.com/Grafritz/brain_dev_firebase_message_plugin.git

#  dart pub publish --dry-run   #// Vérifier avant chaque nouvelle version
#  dart pub login
#  dart pub publish            # Publier la mise à jour

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8


  get: ^4.7.2

  # Run : firebase login | dart pub global activate flutterfire_cli | flutterfire configure
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6

  shared_preferences: ^2.5.3

  # rm -rf ~/.pub-cache/git
  # clear && flutter clean && rm -rf ~/.pub-cache/git && flutter pub get
  brain_dev_tools: ^1.0.8
    #path: /Users/jeanfritzduverseau/_Travaux/Projects/Flutter_Plugins/brain_dev_tools_plugin

  brain_dev_business: ^1.0.8
    #path: /Users/jeanfritzduverseau/_Travaux/Projects/Flutter_Plugins/brain_dev_business_plugin


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      android:
        package: net.braindev.brain_dev_firebase_message
        pluginClass: BrainDevFirebaseMessagePlugin
      ios:
        pluginClass: BrainDevFirebaseMessagePlugin
      web:
        pluginClass: BrainDevFirebaseMessageWeb
        fileName: brain_dev_firebase_message_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
